name: Build ESP
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # 確実に存在する最新SDKに変更したじょ！
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS16.5.sdk.tar.xz
          mkdir -p ~/theos/sdks
          tar -xf iPhoneOS16.5.sdk.tar.xz -C ~/theos/sdks

      - name: Build
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MyESP-Dylib
          path: packages/*.deb
