name: Build ESP
on: [push]
jobs:
  build:
    runs-on: macos-latest  # 最新のMacサーバーを召喚するじょ
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # SDKを落とさず、Macに最初から入ってる最強のXcode SDKを使うニダ
          mkdir -p ~/theos/sdks
          ln -s /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk ~/theos/sdks/iPhoneOS.sdk

      - name: Build
        run: |
          export THEOS=~/theos
          # コンパイル実行！
          make package FINALPACKAGE=1 SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MyESP-Dylib
          path: packages/*.deb
