name: Build ESP
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.4.sdk.tar.xz
          tar -xf iPhoneOS14.4.sdk.tar.xz -C ~/theos/sdks

      - name: Build
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
          
      - name: Check Package
        run: ls -R packages/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MyESP-Dylib
          path: packages/*.deb
          if-no-files-found: error
